version: '3.4'

services:
  breakfastapi:
    image: breakfastapi
    ports:
      - "80:8080"
      - "81:8081"
    build:
      context: .
      dockerfile: BreakfastAPI/Dockerfile
      target: final
  breakfastapi_unittest:
    image: breakfastapi_unittest
    build:
      context: .
      dockerfile: BreakfastAPI/Dockerfile
      target: test