on:
    push:
        branches:
            - '**' 
    workflow_dispatch:
jobs:
    test:
        runs-on: [windows-latest]
        steps:
            - name: Adding markdown
              run: echo "### Hello world! 🚀" >> $GITHUB_STEP_SUMMARY
              shell: bash

